---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.2
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        files: \.(scss)$
        additional_dependencies:
          - "stylelint@13.13.1"
          - "stylelint-config-idiomatic-order@8.1.0"
          - "stylelint-config-prettier@8.0.2"
          - "stylelint-config-recommended-scss@4.3.0"
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint
        entry: markdownlint
        language: node
        types: [markdown]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: htmlhint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        files: \.(js|json)$
        types: [file]
