---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.48.0
    hooks:
      - id: eslint
        files: \.(js|json)$
        args: ["--fix"]
        additional_dependencies:
          - "eslint@8.48.0"
          - "eslint-config-standard@17.1.0"
          - "eslint-config-prettier@9.0.0"
          - "eslint-plugin-import@2.28.1"
          - "eslint-plugin-json@3.1.0"
          - "eslint-plugin-n@16.0.2"
          - "eslint-plugin-promise@6.1.1"

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        files: \.(scss)$
        additional_dependencies:
          - "stylelint@15.10.3"
          - "stylelint-config-standard-scss@10.0.0"

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmlhint

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint

  - repo: local
    hooks:
      - id: super-linter
        name: 'super-linter'
        entry: ./super-linter.sh
        language: system
        pass_filenames: false
